stages:
  - build
  - test

variables:
  IMAGEREF: $CI_REGISTRY/f329-tutoriais/docker:latest

build:
  tags:
    - docker
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGEREF .
    - docker push $IMAGEREF
